// Code generated by MockGen. DO NOT EDIT.
// Source: organizes.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/yukitaka/longlong/internal/entity"
)

// MockOrganizes is a mock of Organizes interface.
type MockOrganizes struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizesMockRecorder
}

// MockOrganizesMockRecorder is the mock recorder for MockOrganizes.
type MockOrganizesMockRecorder struct {
	mock *MockOrganizes
}

// NewMockOrganizes creates a new mock instance.
func NewMockOrganizes(ctrl *gomock.Controller) *MockOrganizes {
	mock := &MockOrganizes{ctrl: ctrl}
	mock.recorder = &MockOrganizesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizes) EXPECT() *MockOrganizesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizes) Create(name string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(int)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizesMockRecorder) Create(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizes)(nil).Create), name)
}

// Find mocks base method.
func (m *MockOrganizes) Find(arg0 int) (*entity.Organize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*entity.Organize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockOrganizesMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockOrganizes)(nil).Find), arg0)
}
